Add Code Review Intro and Suggested Workflow
jabardigitalservice/development-guides pull request #2
Opened 2020-07-12 11:22 UTC by aldidoanta

Create initial explanation of code review and suggested workflow based on biweekly quick wins about code review. Closes #1 .

2020-07-12 18:56 UTC, adrianpdm commented
Tidakkah semestinya list [**ini**](https://github.com/jabardigitalservice/development-guides/blame/586900bea1db0e2a6b8feef94d4cf7f02897be31/git_workflow.md#L21-L27) masuk ke chapter Pull Request, karena isinya berbicara tentang how to perform a pull request instead of how to conduct a review?

2020-07-13 02:37 UTC, sandisunandar99 commented on git_workflow.md
> +## Code Review dan Approval
yang hastag ## code review dan approval <- - bisa dikatakan judul PR juga ga??

2020-07-14 01:47 UTC, yohang88 commented
> Tidakkah semestinya list [**ini**](https://github.com/jabardigitalservice/development-guides/blame/586900bea1db0e2a6b8feef94d4cf7f02897be31/git_workflow.md#L21-L27) masuk ke chapter Pull Request, karena isinya berbicara tentang how to perform a pull request instead of how to conduct a review?

Betul sepakat ini, bagian Workflow lebih cocok masuk ke chapter Pull Request.

2020-07-14 01:56 UTC, yohangdev requested changes
gas

2020-07-14 01:56 UTC, yohang88 commented on git_workflow.md
> +  - Referensi ke ticket yang membahas PR tersebut, misalnya dalam bentuk URL Trello card atau URL GitHub Issue.
Tidak perlu menyebut Trello kayaknya. Cukup task/issue tracker.

2020-07-14 01:56 UTC, yohang88 commented on git_workflow.md
> +5. Setelah source branch yang digunakan untuk PR berhasil di-merge ke target branch (misalnya branch `development`), hapus branch tersebut. Langkah ini tidak perlu dilakukan jika source branch yang d
Kayaknya ada kalimat gantung "Branch development."

Btw bagian "ada setting yang dapat digunakan" ini dituliskan di poin berikutnya, karena merupakan tips.

2020-07-14 05:14 UTC, aldidoanta commented
> Tidakkah semestinya list [**ini**](https://github.com/jabardigitalservice/development-guides/blame/586900bea1db0e2a6b8feef94d4cf7f02897be31/git_workflow.md#L21-L27) masuk ke chapter Pull Request, karena isinya berbicara tentang how to perform a pull request instead of how to conduct a review?

Kang @adrianpdm @yohang88 ok, berarti untuk bagian `Workflow` akan dipindah ke bagian `Pull/Merge Request`, sedangkan bagian `Code Review dan Approval` akan diganti isinya dengan hal-hal yang harus diperhatikan saat code review (dari sisi reviewer maupun Pull Request author)

2020-07-14 05:54 UTC, aldidoanta commented on git_workflow.md
> +## Code Review dan Approval
Ok kang @sandisunandar99 , sesuai feedback tmn2 yang lain, saya pindahkan isinya ke bagian `Pull/Merge Request` ya

2020-07-14 07:06 UTC, aldidoanta commented
Kang @adrianpdm @sandisunandar99 @yohang88 Terima kasih untuk feedbacknya, sudah saya revisi ya.
Deskripsi PR juga saya edit.

2020-07-27 09:47 UTC, adrianpdm approved these changes

2020-07-28 03:00 UTC, merged