Frontend guide
jabardigitalservice/development-guides pull request #3
Opened 2020-07-14 02:50 UTC by maruf12

Review untuk guideline frontend teman-teman 
@yohang88 @Arif9878 @adrianpdm yoslie

2020-07-14 02:54 UTC, yohangdev requested changes
gaaaas

2020-07-14 02:54 UTC, yohang88 commented on frontend.md
> +  * Varible name use Noun
tipo gan, sehahrusnya `variable` kan yes

2020-07-14 02:54 UTC, yohang88 commented on frontend.md
> +* Guideline:
Better coba ditambahkan tools/standar code-linter yang mau dipakai, kan ada banyak ya, mana yang akan dipakai?

2020-07-14 02:55 UTC, adrianpdm commented on frontend.md
> +  * Use PascalCase for file name
ini sudah ada pada rule PascalCase di atasnya

2020-07-14 03:02 UTC, maruf12 commented on frontend.md
> +* Guideline:
siap

2020-07-14 07:03 UTC, aldidoanta approved these changes
Mantap ruf :+1:  untuk iterasi berikutnya, bisa ditambahkan semacam lesson learned atau common mistakes yang sering terjadi selama development di JDS

2020-07-16 03:34 UTC, maruf12 commented
gas gas @yohang88 @aldidoanta @Arif9878 @adrianpdm @yoslie

2020-07-16 03:36 UTC, adrianpdm approved these changes

2020-07-16 09:26 UTC, merged